# On which port Prometheus webserver should be started?
# Default: 25585
server-port=25585

# FabricExporter updates gauge metrics every N milliseconds
# You can change this value if you want metrics to be updated more or less frequently
# Value must be provided in milliseconds, 1 second = 1000 milliseconds
# Default: 1000
update-interval=1000

# Should FabricExporter use Spark mod (https://spark.lucko.me) to collect TPS and MSPT metrics?
# If disabled, TPS and MSPT metrics will not be collected, values of enable-mspt and enable-tps are overridden in this case
# If enabled, Fabric version of Spark must be installed
# Default: true
use-spark=true

# Should FabricExporter register default Hotspot exports?
# This enables advanced metrics for JVM
# Default: true
export-default-jvm-metrics=true

# Should FabricExporter provide only identifier paths without namespaces in metric labels?
# Label values without namespaces look more cleanly, but this could cause conflicts if your mods provide multiple
# identifiers with same paths.
# Default: true
strip-identifier-namespaces=true

# You can disable any metric that registered via MetricRegistry (all metrics by default) using the settings below
# Names of properties consist of "enable" and metric name without prefix and "_" replaced with "-"
# For example, if you want to disable "minecraft_players_online", you should set "enable-players-online" to "false"
# If you can't find property for some metrics, you can manually add it
# All metrics are enabled by default

# Exports amount of currently loaded chunks on server
# Collected by Minecraft
enable-loaded-chunks=true

# Exports count of milliseconds per tick (MSPT)
# Collected by Spark. If enabled, requires Spark to be installed
enable-mspt=true

# Exports count of ticks per second (TPS)
# Collected by Spark. If enabled, requires Spark to be installed
enable-tps=true

# Exports amount of currently online players on your server
# Collected by FabricExporter
enable-players-online=true

# Exports current ping of online players
# Collected by FabricExporter
enable-player-ping=true
# Should FabricExporter collect IP addresses of players?
# If enabled, IP addresses will be collected and exported as a label.
# If disabled, IP addresses will not be collected.
collect-player-ip=false
# Should FabricExporter anonymize IP addresses of players?
# If enabled, the last octet of the IP address will be replaced with "0" (e.g. 127.0.0.1 -> 127.0.0.0)
anonymize-player-ip=true

# Exports amount of currently loaded entities on your server
# Collected by FabricExporter
enable-entities=true

# Exports amount of currently loaded item entities by item type on your server
# Collected by FabricExporter
enable-item-entities=true

# Exports count of handshake requests
# Collected by FabricExporter
enable-handshakes=true

# Exports amount of mob counts from spawn data on your server
# Collected by FabricExporter
enable-spawned-mobs=true

# Exports amount of spawnable chunks on your server.
# Collected by FabricExporter
enable-spawnable-chunks=true